### ISSUE TITLE
screw experimental branch XD ill make it again later

### ISSUE THREAD

**Issue by MajorPlayz** [PeaceOfDevs/ServerCore#2]
now could someone delete it for me please thx idk how haha :D also my phone is old and outdated so it won't allow the JavaScript techniques used on github sorry XD

**Comment by VCraftMCPE** [comment]
OK

**Comment by MajorPlayz** [comment]
K i added again but cld u delete all the files in it except readme.md please as i dont have acess to a linux machine. (You cant delete folders on the web interface)

Thx :D

**Comment by MajorPlayz** [comment]
And im on my tab now which is android m so does have javascript but anyway still cant XD
